// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewReview struct {
	Body      string `json:"body"`
	AuthorID  string `json:"authorID"`
	ProductID string `json:"productID"`
}

type Product struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	ID      string   `json:"id"`
	Body    *string  `json:"body,omitempty"`
	Author  *User    `json:"author,omitempty"`
	Product *Product `json:"product,omitempty"`
}

type UpdateReview struct {
	Body      *string `json:"body,omitempty"`
	ProductID *string `json:"productID,omitempty"`
}

type User struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews,omitempty"`
}

func (User) IsEntity() {}
