package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"database/sql"
	"fmt"
	"users/graph/model"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	// Prepare the SQL query
	query := `SELECT id, name, email FROM users WHERE id = ?`

	// Create a variable to store the user data
	var user model.User

	// Execute the query
	err := r.DB.QueryRowContext(ctx, query, id).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			// No user found for given ID
			return nil, nil
		}
		// Other DB error
		return nil, fmt.Errorf("failed to query user: %w", err)
	}

	// Return the found user
	return &user, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
