package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	errorhandler "users/errorHandler"
	"users/graph/model"
	"users/saga"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*model.User, error) {
	query := `INSERT INTO users (name, email) VALUES (?, ?)`

	result, err := r.DBUser.ExecContext(ctx, query, name, email)
	if err != nil {
		return nil, errorhandler.New("INSERTION_FAILED", "failed to insert user")
	}

	// Get the last inserted ID
	id, err := result.LastInsertId()
	if err != nil {
		return nil, errorhandler.New("ID_FETCH_FAILED", "failed to retrieve inserted ID")
	}

	// Build and return the created user
	user := &model.User{
		ID:    fmt.Sprintf("%v", id), // Convert int64 → string if your GraphQL ID type is string
		Name:  name,
		Email: email,
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUser) (*model.User, error) {
	row := r.DBUser.QueryRowContext(ctx, `
		SELECT id, name, email
		FROM users
		WHERE id = ?
	`, id)

	var (
		userID string
		name   sql.NullString
		email  sql.NullString
	)

	if err := row.Scan(&userID, &name, &email); err != nil {
		if err == sql.ErrNoRows {
			return nil, errorhandler.New("NOT_FOUND", fmt.Sprintf("user with id %s not found", id))
		}
		return nil, errorhandler.New("NOT_FOUND", "failed to fetch user")
	}

	newName := name.String
	if input.Name != nil {
		newName = *input.Name
	}

	newEmail := email.String
	if input.Email != nil {
		newEmail = *input.Email
	}

	_, err := r.DBUser.ExecContext(ctx, `
		UPDATE users
		SET name = ?, email = ?
		WHERE id = ?
	`, newName, newEmail, id)
	if err != nil {
		return nil, errorhandler.New("UPDATE_FAILED", "failed to update user")
	}

	updated := &model.User{
		ID:    id,
		Name:  newName,
		Email: newEmail,
	}

	return updated, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.User, error) {
	row := r.DBUser.QueryRowContext(ctx, `
		SELECT id, name, email
		FROM users
		WHERE id = ?
	`, id)

	var (
		userID string
		name   sql.NullString
		email  sql.NullString
	)

	if err := row.Scan(&userID, &name, &email); err != nil {
		if err == sql.ErrNoRows {
			return nil, errorhandler.New("NOT_FOUND", fmt.Sprintf("user with id %s not found", id))
		}
		return nil, errorhandler.New("NOT_FOUND", "failed to fetch user before delete")
	}

	_, err := r.DBUser.ExecContext(ctx, `
		DELETE FROM users
		WHERE id = ?
	`, id)
	if err != nil {
		return nil, errorhandler.New("DELETION_FAILED", "failed to delete user")
	}

	deleted := &model.User{
		ID:    userID,
		Name:  name.String,
		Email: email.String,
	}

	return deleted, nil
}

// CreateUserWithSettings is the resolver for the createUserWithSettings field.
func (r *mutationResolver) CreateUserWithSettings(ctx context.Context, input model.CreateUser) (*model.User, error) {
	var userID string

	s := saga.Saga{
		Steps: []saga.SagaStep{
			{
				Name: "CreateUser",
				Original: func() (string, error) {
					res, err := r.DBUser.Exec(`INSERT INTO users (name, email) VALUES (?, ?)`, input.Name, input.Email)
					if err != nil {
						return "", err
					}
					id, _ := res.LastInsertId()
					userID = fmt.Sprintf("%v", id)
					log.Printf("Created user with ID %v", userID)
					return userID, nil
				},
				Compensation: func(id string) error {
					log.Printf("Deleting user with ID %v", id)
					_, err := r.DBUser.Exec(`DELETE FROM users WHERE id = ?`, id)
					return err
				},
			},
			{
				Name: "CreateUserSettings",
				Original: func() (string, error) {
					res, err := r.DBUserSetting.Exec(`
						INSERT INTO user_settings (user_id, theme, language, notifications_enabled)
						VALUES (?, ?, ?, ?)`,
						userID, input.Settings.Theme, input.Settings.Language, input.Settings.NotificationsEnabled,
					)
					if err != nil {
						return "", err
					}
					settingsID, _ := res.LastInsertId()
					log.Printf("Created user_settings for user %v (ID %v)", userID, settingsID)
					return fmt.Sprintf("%v", settingsID), nil
				},
				Compensation: func(id string) error {
					log.Printf("Deleting user_settings ID %v", id)
					_, err := r.DBUserSetting.Exec(`DELETE FROM user_settings WHERE id = ?`, id)
					return err
				},
			},
		},
	}

	if err := s.Run(); err != nil {
		return nil, err
	}

	return &model.User{
		ID:    userID,
		Name:  input.Name,
		Email: input.Email,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	query := `SELECT id, name, email FROM users`

	rows, err := r.DBUser.QueryContext(ctx, query)
	if err != nil {
		return nil, errorhandler.New("DB_ERROR", "failed to query users")
	}
	defer rows.Close()

	var users []*model.User

	for rows.Next() {
		var user model.User
		if err := rows.Scan(&user.ID, &user.Name, &user.Email); err != nil {
			return nil, errorhandler.New("DB_ERROR", "failed to scan user")
		}
		users = append(users, &user)
	}

	if err := rows.Err(); err != nil {
		return nil, errorhandler.New("DB_ERROR", "row iteration error")
	}

	return users, nil
}

// Settings is the resolver for the settings field.
func (r *userResolver) Settings(ctx context.Context, obj *model.User) (*model.UserSettings, error) {
	row := r.DBUserSetting.QueryRowContext(ctx, `
		SELECT id, user_id, theme, language, notifications_enabled
		FROM user_settings
		WHERE user_id = ?
	`, obj.ID)

	var s model.UserSettings
	err := row.Scan(&s.ID, &s.UserID, &s.Theme, &s.Language, &s.NotificationsEnabled)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil // no settings found
		}
		return nil, fmt.Errorf("query user settings: %w", err)
	}

	return &s, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
