package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"database/sql"
	"fmt"
	"users/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*model.User, error) {
	query := `INSERT INTO users (name, email) VALUES (?, ?)`

	result, err := r.DB.ExecContext(ctx, query, name, email)
	if err != nil {
		return nil, fmt.Errorf("failed to insert user: %w", err)
	}

	// Get the last inserted ID
	id, err := result.LastInsertId()
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve inserted ID: %w", err)
	}

	// Build and return the created user
	user := &model.User{
		ID:    fmt.Sprintf("%d", id), // Convert int64 → string if your GraphQL ID type is string
		Name:  name,
		Email: email,
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUser) (*model.User, error) {
	row := r.DB.QueryRowContext(ctx, `
		SELECT id, name, email
		FROM users
		WHERE id = ?
	`, id)

	var (
		userID string
		name   sql.NullString
		email  sql.NullString
	)

	if err := row.Scan(&userID, &name, &email); err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user with id %s not found", id)
		}
		return nil, fmt.Errorf("failed to fetch user: %w", err)
	}

	newName := name.String
	if input.Name != nil {
		newName = *input.Name
	}

	newEmail := email.String
	if input.Email != nil {
		newEmail = *input.Email
	}

	_, err := r.DB.ExecContext(ctx, `
		UPDATE users
		SET name = ?, email = ?
		WHERE id = ?
	`, newName, newEmail, id)
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	updated := &model.User{
		ID:    id,
		Name:  newName,
		Email: newEmail,
	}

	return updated, nil

}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.User, error) {
	row := r.DB.QueryRowContext(ctx, `
		SELECT id, name, email
		FROM users
		WHERE id = ?
	`, id)

	var (
		userID string
		name   sql.NullString
		email  sql.NullString
	)

	if err := row.Scan(&userID, &name, &email); err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user with id %s not found", id)
		}
		return nil, fmt.Errorf("failed to fetch user before delete: %w", err)
	}

	_, err := r.DB.ExecContext(ctx, `
		DELETE FROM users
		WHERE id = ?
	`, id)
	if err != nil {
		return nil, fmt.Errorf("failed to delete user: %w", err)
	}

	deleted := &model.User{
		ID:    userID,
		Name:  name.String,
		Email: email.String,
	}

	return deleted, nil

}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	query := `SELECT id, name, email FROM users`

	rows, err := r.DB.QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to query users: %w", err)
	}
	defer rows.Close()

	var users []*model.User

	for rows.Next() {
		var user model.User
		if err := rows.Scan(&user.ID, &user.Name, &user.Email); err != nil {
			return nil, fmt.Errorf("failed to scan user: %w", err)
		}
		users = append(users, &user)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("row iteration error: %w", err)
	}

	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
