package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"database/sql"
	"fmt"
	"products/graph/model"
	"strconv"
)

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id string) (*model.Product, error) {
	// Convert the string ID from GraphQL into an integer
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	// SQL query
	query := `SELECT id, name, price FROM products WHERE id = ?`

	// Prepare a Product model variable
	var product model.Product

	// Execute query
	err = r.DB.QueryRowContext(ctx, query, productID).Scan(
		&product.ID,
		&product.Name,
		&product.Price,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			// No product found
			return nil, nil
		}
		return nil, fmt.Errorf("failed to query product: %w", err)
	}

	// Return the found product
	return &product, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
